### ISSUE TITLE
Background color getting ignored in customizer

### ISSUE THREAD

**Issue by tareiking** [tareiking/OM-Connect-Theme#17]
Suspect this is part of the attempts to sanitize the color :)

**Comment by zambra11** [comment]
You've got two "body {background: #xxxxxx}" in your style.css. It worked when I changed the color manually from the second one.

**Comment by tareiking** [comment]
Thanks @zambra11, I'll take another look at this - this week.

**Comment by tareiking** [comment]
Also reported here : https://wordpress.org/support/topic/background-color-not-modifiable
