### ISSUE TITLE
Show full post in home-page

### ISSUE THREAD

**Issue by zambrinf** [tareiking/OM-Connect-Theme#18]
Hello, I'm trying to show all posts in full-lenght in the home-page, but I'm not finding how to do it, there's no <?php the_content('Read More'); ?> to change... 

How do I do it?

**Comment by tareiking** [comment]
Hi @zambrinf - apologies for the late response.

You can try removing the is_home() argument on https://github.com/tareiking/OM-Connect-Theme/blob/master/parts/content.php#L23

That should give you the full entry content and not the excerpt. 

Let me know if how that goes for you
